name: Deploy to production

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install deps
        run: yarn

      - name: Deploy English version
        run: NOW_ORG_ID=${{ secrets.NOW_ORG_ID }} NOW_PROJECT_ID=${{ secrets.NOW_PROJECT_EN }} yarn deploy:now --token ${{ secrets.ZEIT_TOKEN }}

      - name: Deploy Portuguese version
        run: NOW_ORG_ID=${{ secrets.NOW_ORG_ID }} NOW_PROJECT_ID=${{ secrets.NOW_PROJECT_PT }} yarn deploy:now --token ${{ secrets.ZEIT_TOKEN }}
