name: Deploy to production

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache frontend node modules
        id: cache-frontend
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.cache-frontend.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install deps
        run: yarn

      - name: Deploy English version
        run: NOW_ORG_ID=${{ secrets.NOW_ORG_ID }} NOW_PROJECT_ID=${{ secrets.NOW_PROJECT_EN }} yarn deploy:now --token ${{ secrets.ZEIT_TOKEN }}

      - name: Deploy Portuguese version
        run: NOW_ORG_ID=${{ secrets.NOW_ORG_ID }} NOW_PROJECT_ID=${{ secrets.NOW_PROJECT_PT }} yarn deploy:now --token ${{ secrets.ZEIT_TOKEN }}
